package org.freedesktop.gstreamer.lowlevel.enums;

public enum NiceComponentState {
	NICE_COMPONENT_STATE_DISCONNECTED,
	NICE_COMPONENT_STATE_GATHERING,
	NICE_COMPONENT_STATE_CONNECTING,
	NICE_COMPONENT_STATE_CONNECTED,
	NICE_COMPONENT_STATE_READY,
	NICE_COMPONENT_STATE_FAILED
}
