package org.freedesktop.gstreamer.lowlevel.enums;


public enum NiceCompatibility  {
	NICE_COMPATIBILITY_RFC5245,
	NICE_COMPATIBILITY_GOOGLE,
	NICE_COMPATIBILITY_MSN,
	NICE_COMPATIBILITY_WLM2009,
	NICE_COMPATIBILITY_OC2007,
	NICE_COMPATIBILITY_OC2007R2;

}
